In [ ]:
import pandas as pd 
import numpy as np
from bs4 import BeautifulSoup 
import requests 
import re
# import lxml

In [ ]:
### #skipping the HTTP call part for now & using the downloaded HTML file#
## NB: when uncommenting check the utf encoding 

#url= "https://allocreche.fr/75/paris/micro-creche"
#url2 = "https://monenfant.fr/que-recherchez-vous?structure=EAJE&location=Paris,%20%C3%8Ele-de-France,%20FRA&x=2.35245810663&y=48.856413872242&radius=2000"
# r = requests.get(url, headers={"User-Agent": "Mozilla/5.0"})
# r.encoding = "utf-8"  
#soup = BeautifulSoup(r.text, "html.parser")

In [ ]:




with open("src/Allocreche/MicroCrechesParis.html", encoding="utf-8") as f:
    soup = BeautifulSoup(f.read(), "html.parser")

#soup = BeautifulSoup(filehandle,"html.parser")

allocreche = soup.select('div[itemtype="http://schema.org/LocalBusiness"]')
allocreche.encoding = "utf-8"
   
def safe_text(el):
    return el.get_text(strip=True) if el else ""

rows_ac = []

for b in soup.select('div[itemtype="http://schema.org/LocalBusiness"]'):
    name   = safe_text(b.select_one('[itemprop="name"]'))
    street = safe_text(b.select_one('[itemprop="streetAddress"]'))
    postal = safe_text(b.select_one('[itemprop="postalCode"]'))
    city   = safe_text(b.select_one('[itemprop="addressLocality"]'))

    # optional: skip empty cards
    if not name:
        continue
    
    
    rows_ac.append({
        "name": name,
        "street": street,
        "postal": postal,
        "city": city
    })

df = pd.DataFrame(rows_ac)
df

                   name                            street postal   city
0   Baboune Batignolles                   35 rue Brochant  75015  Paris
1     Baboune Boissière                  17 rue Boissière  75116  Paris
2      Baboune Charonne                22 rue Emile Lepeu  75011  Paris
3   Baboune Chemin Vert                     40 rue Servan  75011  Paris
4         Baboune Dumas                   28 rue Planchat  75020  Paris
5     Baboune Faidherbe               30 rue de Montreuil  75011  Paris
6         Baboune Javel                     16 rue Cauchy  75015  Paris
7        Baboune Martel                  11-13 rue Martel  75010  Paris
8   Baboune Messageries             7 rue des Messageries  75010  Paris
9    Baboune Providence        26-28 rue de la Providence  75013  Paris
10       Baboune Temple  6-8 rue Notre Damme des Nazareth  75003  Paris
11     Baboune Voltaire                    28 rue Basfroi  75011  Paris

In [15]:
with open("src/MonEnfant/MonEnfant.html", encoding="utf-8") as f:
    soup = BeautifulSoup(f.read(), "html.parser")


rows_me = []

for card in soup.select("div.structure-card"):
    name = safe_text(card.select_one("h4.title-content p"))
    address = safe_text(card.select_one("span.address-content"))

    # phone: first contact-txt if present
    #phone = ""
    contact_spans = card.select("div.contact-card span.contact-txt")
    if contact_spans:
        phone = safe_text(contact_spans[0])

    if not name:
        continue  # skip broken cards

    rows_me.append({
        "name": name,
        "street": address,
        "postal": "75000",
        "city": "Paris"
        #"phone": phone,
        ""
    })

df = pd.DataFrame(rows_me)
df

,name,street,postal,city
0,"CC MUNICIPALE LOBAU, HOTEL DE VILLE",3 Rue Lobau 75004 PARIS,75000,Paris
1,HG MUNICIPALE LOBAU,3 Rue Lobau 75004 PARIS,75000,Paris
2,CC MUNICIPALE BARRES,7-9 Rue des Barres 75004 PARIS,75000,Paris
3,CP ASSOCIATIVE DU MARAIS,8 Rue François Miron 75004 PARIS,75000,Paris
4,CC MUNICIPALE MOUSSY,2-6 Rue de Moussy 75004 PARIS,75000,Paris
5,CC MUNICIPALE BLANCS-MANTEAUX,21 Rue des Blancs Manteaux 75004 PARIS,75000,Paris
6,CP LES JEUNES HEURES,4 Rue du Pas de la Mule 75004 PARIS,75000,Paris
7,"CC MUNICIPALE RAMBUTEAU (6 RUE RAMBUTEAU), SAI...",6 Rue Rambuteau 75003 PARIS,75000,Paris
8,CC MUNICIPALE FRANCS BOURGEOIS,22 bis Rue des Francs Bourgeois 75003 PARIS,75000,Paris
9,HG MUNICIPALE FRANCS BOURGEOIS,22 bis Rue des Francs Bourgeois 75003 PARIS,75000,Paris
10,MA PARIS 3 HAUDRIETTES,3 Rue des Haudriettes 75003 PARIS,75000,Paris
11,CC MUNICIPALE BRANTÔME,21 Rue Brantôme 75003 PARIS,75000,Paris
12,CF MUNICIPALE JARDINS SAINT PAUL,22 ter Rue des Jardins St Paul 75004 PARIS,75000,Paris
13,HG MUNICIPALE JARDINS SAINT-PAUL,22 bis Rue des Jardins Saint Paul 75004 PARIS,75000,Paris
14,CC LE FIGUIER,6 Rue de l'Ave Maria 75004 PARIS,75000,Paris
15,"CC MUNICIPALE EGINHARD, CHARLEMAGNE",8 Rue Eginhard 75004 PARIS,75000,Paris
16,CC MUNICIPALE PRÊTRES SAINT-SÉVERIN,6-12 Rue des Prêtres St Séverin 75005 PARIS,75000,Paris
17,MA SECRETS D'ENFANTS,5 Rue CHARLOT 75003 PARIS,75000,Paris
18,CC PERLE,16 Rue de la Perle 75003 PARIS,75000,Paris
19,MA LE TEMPS DES OURS,8 Rue de Montmorency 75003 PARIS,75000,Paris
20,HG MUNICIPALE PROUVAIRES,8 Rue des Prouvaires 75001 PARIS,75000,Paris
21,CC MARTIN,220 Rue Saint Martin 75003 PARIS,75000,Paris
22,MA MARTIN,220 Rue Saint Martin 75003 PARIS,75000,Paris
23,"CC MUNICIPALE RAMBUTEAU (132 RUE RAMBUTEAU), L...",132 Rue Rambuteau 75001 PARIS,75000,Paris
24,CC MUNICIPALE ARBRE SEC,17 bis Rue de l'Arbre sec 75001 PARIS,75000,Paris
25,HG MUNICIPALE GRAVILLIERS,24 Rue des Gravilliers 75003 PARIS,75000,Paris
26,"CF MUNICIPALE BAILLY, TURBIGO",2 Rue Bailly 75003 PARIS,75000,Paris
27,CF TURBIGO,50 Rue de Turbigo 75003 PARIS,75000,Paris
28,CC MUNICIPALE GRENETA,44 Rue Greneta 75002 PARIS,75000,Paris
29,CC MUNICIPALE VALETTE,11 Rue Valette 75005 PARIS,75000,Paris